name: HelloEddie
favicon: null
layout_spectrum: 0.83879
typography_spectrum: 0.31792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbd6da'
    - '#bbb4ab'
    - '#73767d'
    - '#919296'
    - '#3d383e'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.9719532588496804
  rhythmicContrast: 0.75
purpose: []
