name: HelloEddie
favicon: null
layout_spectrum: 0.98052
typography_spectrum: 0.65855
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#79a09f'
    - '#dddcc9'
    - '#f2d057'
    - '#663a1e'
    - '#ed793e'
  brandStrength: 0.0625
  lightness: 0.2789988873992115
  saturation: 0.9719532588496804
  rhythmicContrast: 0.75
purpose: []
