name: HelloEddie
favicon: null
layout_spectrum: 0.38610778166912496
typography_spectrum: 0.4992687173653394
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9043963646981865
  lightness: 0.2789988873992115
  saturation: 0.9719532588496804
  rhythmicContrast: 0.7342649351339787
purpose: []
