name: HelloEddie
favicon: null
layout_spectrum: 0.32304
typography_spectrum: 0.30422
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#79a09f'
    - '#dddcc9'
    - '#f2d057'
    - '#663a1e'
    - '#ed793e'
  brandStrength: 1
  lightness: 1
  saturation: 0.9719532588496804
  rhythmicContrast: 1
purpose: []
