name: HelloEddie
favicon: null
layout_spectrum: 0.83879
typography_spectrum: 0.47934
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#79a09f'
    - '#dddcc9'
    - '#f2d057'
    - '#663a1e'
    - '#ed793e'
  brandStrength: 0.875
  lightness: 1
  saturation: 0.9719532588496804
  rhythmicContrast: 0.75
purpose: []
